name: dadguide_admin
description: Front end for DadGuide administrative tools

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Http downloads
  dio: ^3.0.7
  http: ^0.12.0

  # Logging
  flutter_fimber: ^0.3.2

  # Injection
  provider: ^3.2.0

  # Image loading and caching
  cached_network_image: ^2.0.0-rc
  flutter_cache_manager: 1.1.3

  # Opening URLs
  url_launcher: ^5.4.0

  # Protocol buffer support
  protobuf: any

  # Icons
  cupertino_icons: ^0.1.3
  flutter_icons: ^1.0.0

  # Dependency injection
  # TODO: look into upgrading to 3.0.3
  get_it: ^1.0.3+2

  # Data object generation
  json_annotation: ^3.0.0

  # URL routing
  fluro: ^1.5.1

  # Date/internationalization stuff
  intl: ^0.16.0

  dadguide2:
    path: ../dadguide2
#   git: git://github.com/nachoapps/dadguide-flutter.git

  # Only used to init pref service
  preferences: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  json_serializable: ^3.2.3

flutter:
  uses-material-design: true

